### ISSUE TITLE
Hierarchical Navigable Small Worlds Support 

### ISSUE THREAD

**Issue by ks0m1c** [pgvector/pgvector-elixir#7]
pgvector 0.5.0 release introduced the hnsw index type which supports 

- “Build as you go”: Can create an index on an empty table and add vectors as you go without impacting recall. This is different from ivfflat, where you first need to load your vectors before building the index to find optimal centers for better recall. As you add more data to your ivfflat index, you may also need to re-index to find updated centers.

- Update and delete: Update and delete vectors from the index, as part of standard UPDATE and DELETE queries.

- Concurrent inserts: Concurrently insert values into the index, making it easier to simultaneously load data from multiple sources.

Support with Ecto should work to express queries and migrations
`
SET hnsw.ef_search TO 20;
SELECT *
FROM vecs
ORDER BY q <-> embedding
LIMIT 10;
`
and creation of index
`CREATE INDEX ON vecs USING hnsw(embedding vector_l2_ops) WITH (m=16, ef_construction=64);`

**Comment by ankane** [comment]
Hi @KosmonautX, nothing additional is needed to support it.
